[tool.poetry]
name = "corrigan"
version = "0.1.0"
description = ""
authors = ["spectrejim <shafersj@jbu.edu>"]

[tool.poetry.dependencies]
python = "^3.7"
regex = "^2020.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
